In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df=pd.read_csv('spam.csv', encoding='latin-1')

In [68]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [5]:
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [6]:
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
df['v1']=df['v1'].replace({'ham':0,'spam':1})

<ipython-input-7-910c68ad3135>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['v1']=df['v1'].replace({'ham':0,'spam':1})


In [8]:
df.rename(columns={'v1':'type'},inplace=True)

In [9]:
df.rename(columns={'v2':'message'},inplace=True)

In [10]:
pip install nltk

In [11]:
pip install gensim

In [14]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Download the 'wordnet' dataset
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet') # This line downloads the required 'wordnet' dataset
nltk.download('punkt_tab')

def pre_processing(text):
  text=text.lower()
  pattern = r"http\S+|www\S+|[^a-zA-Z0-9\s]"
  text=re.sub(pattern,'',text)
  tokens=word_tokenize(text)
  stop_words=set(stopwords.words('english'))
  tokens=[word for word in tokens if word not in stop_words]
  lemmatizer=WordNetLemmatizer()
  tokens=[lemmatizer.lemmatize(word) for word in tokens]
  return ' '.join(tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [15]:
df['message']=df['message'].apply(pre_processing)

In [16]:
df.head()

type                                            message
0     0  go jurong point crazy available bugis n great ...
1     0                            ok lar joking wif u oni
2     1  free entry 2 wkly comp win fa cup final tkts 2...
3     0                u dun say early hor u c already say
4     0           nah dont think go usf life around though

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Assuming `df['message']` contains your text data
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the entire column at once
tfidf_matrix = tfidf_vectorizer.fit_transform(df['message'])

# Convert the TF-IDF matrix to a dense array (optional, for inspection)
dense_matrix = tfidf_matrix.toarray()

# Print feature names and TF-IDF matrix
print("Feature Names:", tfidf_vectorizer.get_feature_names_out())
print("TF-IDF Matrix (Dense):")
print(dense_matrix)


Feature Names: ['008704050406' '0089my' '0121' ... 'zoom' 'zouk' 'zyada']
TF-IDF Matrix (Dense):
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [20]:
x=dense_matrix

In [21]:
y=df['type']

In [ ]:
#applying logistic regression

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=LogisticRegression()
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print('accuracy :', accuracy)

accuracy : 0.9443946188340807


In [27]:
messages = df['message']


max_seq = max(len(message.split()) for message in messages)

max_seq

80

In [28]:
pip install tensorflow

In [33]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Extract the 'message' column
messages = df['message']

# Initialize and fit the tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(messages.tolist())

# Convert texts to sequences
sequences = tokenizer.texts_to_sequences(messages.tolist())

# Pad the sequences to a fixed length (e.g., 80)
padded_sequences = pad_sequences(sequences, maxlen=80)

# Output the result
print(padded_sequences)


[[   0    0    0 ...   14 3968   74]
 [   0    0    0 ...  352    1 1640]
 [   0    0    0 ... 2617  300 2618]
 ...
 [   0    0    0 ... 1090 8750 3963]
 [   0    0    0 ...  842    1   12]
 [   0    0    0 ... 2318  391  169]]


In [34]:
x=padded_sequences
y=df['type']

In [37]:
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding, SpatialDropout1D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import regularizers
import numpy as np

# Assuming `padded_sequences` and `labels` are ready
# If you don't have labels, you'll need to define them. For example, for binary classification:
labels = df['type']  # Replace with your actual label column

# Split the dataset into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(padded_sequences, labels, test_size=0.2, random_state=42)

# Neural Network Model (Simple LSTM model)
model = Sequential()

# Adding an embedding layer (use vocab_size = len(tokenizer.word_index) + 1)
vocab_size = len(tokenizer.word_index) + 1
embedding_dim = 100

model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=80))

# Adding SpatialDropout1D to prevent overfitting
model.add(SpatialDropout1D(0.2))

# Adding LSTM layer
model.add(LSTM(50, dropout=0.2, recurrent_dropout=0.2))

# Adding Dense layer for output
model.add(Dense(1, activation='sigmoid'))  # Use 'softmax' for multiclass classification

# Compile the model
model.compile(loss='binary_crossentropy', optimizer=Adam(), metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=5, batch_size=64, validation_data=(X_test, y_test))

# Evaluate the model on test data
score, accuracy = model.evaluate(X_test, y_test, verbose=1)

print(f"Test accuracy: {accuracy*100:.2f}%")


Epoch 1/5
70/70 ━━━━━━━━━━━━━━━━━━━━ 9s 87ms/step - accuracy: 0.8585 - loss: 0.3918 - val_accuracy: 0.9713 - val_loss: 0.1483
Epoch 2/5
70/70 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - accuracy: 0.9787 - loss: 0.1004 - val_accuracy: 0.9821 - val_loss: 0.0625
Epoch 3/5
70/70 ━━━━━━━━━━━━━━━━━━━━ 5s 72ms/step - accuracy: 0.9928 - loss: 0.0372 - val_accuracy: 0.9830 - val_loss: 0.0591
Epoch 4/5
70/70 ━━━━━━━━━━━━━━━━━━━━ 6s 78ms/step - accuracy: 0.9937 - loss: 0.0220 - val_accuracy: 0.9821 - val_loss: 0.0538
Epoch 5/5
70/70 ━━━━━━━━━━━━━━━━━━━━ 6s 89ms/step - accuracy: 0.9980 - loss: 0.0084 - val_accuracy: 0.9812 - val_loss: 0.0633
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9821 - loss: 0.0642
Test accuracy: 98.12%


In [ ]:
#best method is logistic regreesion as model becomes overfit on lstm with 98% accuracy